version: '2'
services:
  postgres:
    image: $POSTGRES_IMG
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data