spring:
  application.name: junit-workshop2
  liquibase.enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=junit
    username: junit_user
    password: junit_psw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        criteria.literal_handling_mode: BIND
    hibernate:
      ddl-auto: none
    default_schema: junit
    show-sql: false
    open-in-view: false
    generate-ddl: false

---
spring:
  config:
    activate:
      on-profile: "test"
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=junit
    user: junit_user
    password: junit_psw
    change-log: classpath:db/changelog/database-changelog.xml